### ISSUE TITLE
.

### ISSUE THREAD

**Issue by muhiris** [Ahmed-Mohamed-Nassar/HTML_and_CSS_Template_two#1]

**Comment by muhiris** [comment]
I was saying Follow my github account.

**Comment by Ahmed-Mohamed-Nassar** [comment]
Okay Follow me and I follow you on GitHub Sent from Android deviceOn Jul 2, 2022 5:43 PM, Muhammad Haris ***@***.***> wrote:
I was saying Follow my github account.

**Comment by muhiris** [comment]
Done Now your turn.
